import React, { useState, useEffect } from 'react';
import { 
  X, 
  RotateCcw, 
  CheckCircle2, 
  ExternalLink, 
  Copy, 
  Check, 
  Terminal, 
  Globe, 
  Code2, 
  Database, 
  MessageSquare, 
  Sparkles,
  ArrowRight,
  Laptop,
  Smartphone
} from 'lucide-react';
import { Button } from '../ui/Button';
import { BrandLogo } from '../brand/BrandLogo';

interface WebsiteBuilderModalProps {
  isOpen: boolean;
  onClose: () => void;
}

interface StepLog {
  id: string;
  step: string;
  connector: 'github' | 'claude' | 'supabase' | 'deepseek' | 'vercel' | 'slack';
  title: string;
  detail: string;
  status: 'pending' | 'running' | 'completed';
  timestamp: string;
}

export const WebsiteBuilderModal: React.FC<WebsiteBuilderModalProps> = ({ isOpen, onClose }) => {
  const [pipelineState, setPipelineState] = useState<'idle' | 'running' | 'completed'>('idle');
  const [currentStepIndex, setCurrentStepIndex] = useState(0);
  const [activeTab, setActiveTab] = useState<'preview' | 'code' | 'logs'>('preview');
  const [previewDevice, setPreviewDevice] = useState<'desktop' | 'mobile'>('desktop');
  const [subscriberEmail, setSubscriberEmail] = useState('');
  const [isSubscribed, setIsSubscribed] = useState(false);
  const [copiedCode, setCopiedCode] = useState(false);
  const websiteTopic = 'Frontier AI Agent Orchestrator SaaS';

  const steps: StepLog[] = [
    {
      id: 'step-1',
      step: 'Step 1/6',
      connector: 'github',
      title: 'GitHub Connector: Repository Sync',
      detail: 'Cloned starter template from nexus-org/saas-website-template (main branch) at commit #48f102.',
      status: currentStepIndex > 0 ? 'completed' : currentStepIndex === 0 && pipelineState === 'running' ? 'running' : 'pending',
      timestamp: '00:00.2s',
    },
    {
      id: 'step-2',
      step: 'Step 2/6',
      connector: 'claude',
      title: 'Claude 3.5 Sonnet: AST Code Synthesis',
      detail: 'Synthesized responsive React 18 & Tailwind components (Hero, Features, Pricing, and Newsletter form).',
      status: currentStepIndex > 1 ? 'completed' : currentStepIndex === 1 && pipelineState === 'running' ? 'running' : 'pending',
      timestamp: '00:01.4s',
    },
    {
      id: 'step-3',
      step: 'Step 3/6',
      connector: 'supabase',
      title: 'Supabase Connector: Database & RLS Migration',
      detail: 'Executed PostgreSQL DDL: Created subscribers and inquiries tables with tenant Row-Level Security policies.',
      status: currentStepIndex > 2 ? 'completed' : currentStepIndex === 2 && pipelineState === 'running' ? 'running' : 'pending',
      timestamp: '00:02.1s',
    },
    {
      id: 'step-4',
      step: 'Step 4/6',
      connector: 'deepseek',
      title: 'DeepSeek-R1: Zero-Trust Security Audit',
      detail: 'Scanned markup for XSS injection vectors, audited auth boundary, and verified cryptographic tokens. 0 vulnerabilities found.',
      status: currentStepIndex > 3 ? 'completed' : currentStepIndex === 3 && pipelineState === 'running' ? 'running' : 'pending',
      timestamp: '00:02.8s',
    },
    {
      id: 'step-5',
      step: 'Step 5/6',
      connector: 'vercel',
      title: 'Vercel Connector: Production Edge Deployment',
      detail: 'Bundled production assets, optimized images, and deployed to live domain: https://nexus-generated-website.vercel.app',
      status: currentStepIndex > 4 ? 'completed' : currentStepIndex === 4 && pipelineState === 'running' ? 'running' : 'pending',
      timestamp: '00:03.9s',
    },
    {
      id: 'step-6',
      step: 'Step 6/6',
      connector: 'slack',
      title: 'Slack Connector: Deployment Notification',
      detail: 'Dispatched interactive deployment card to #nexus-alerts with live URL, git diff, and security pass score (100/100).',
      status: currentStepIndex >= 5 && pipelineState === 'completed' ? 'completed' : currentStepIndex === 5 && pipelineState === 'running' ? 'running' : 'pending',
      timestamp: '00:04.4s',
    },
  ];

  const handleRunPipeline = () => {
    setPipelineState('running');
    setCurrentStepIndex(0);
    setIsSubscribed(false);

    let step = 0;
    const interval = setInterval(() => {
      step += 1;
      if (step <= 5) {
        setCurrentStepIndex(step);
      } else {
        clearInterval(interval);
        setPipelineState('completed');
        setActiveTab('preview');
      }
    }, 850);
  };

  useEffect(() => {
    if (isOpen && pipelineState === 'idle') {
      handleRunPipeline();
    }
  }, [isOpen]);

  const handleSubscribe = (e: React.FormEvent) => {
    e.preventDefault();
    if (!subscriberEmail) return;
    setIsSubscribed(true);
  };

  const sampleWebsiteCode = `// Generated by Claude 3.5 Sonnet & Deployed via Vercel Connector
import React, { useState } from 'react';

export default function GeneratedLandingPage() {
  const [email, setEmail] = useState('');
  const [status, setStatus] = useState('');

  return (
    <div className="min-h-screen bg-slate-50 text-slate-900 font-sans">
      <header className="px-6 py-4 flex items-center justify-between border-b border-slate-200 bg-white">
        <div className="font-bold text-lg tracking-tight text-indigo-600">NEXUS · NOVA</div>
        <nav className="flex gap-6 text-sm font-medium text-slate-600">
          <a href="#features">Features</a>
          <a href="#pricing">Pricing</a>
        </nav>
      </header>
      <main className="max-w-5xl mx-auto px-6 py-20 text-center">
        <span className="text-xs font-bold text-indigo-600 uppercase tracking-widest bg-indigo-50 px-3 py-1 rounded-full">
          Autonomous Multi-Agent Power
        </span>
        <h1 className="text-5xl font-extrabold tracking-tight mt-4 text-slate-950">
          Supercharge your workflow with connected agents.
        </h1>
        <p className="mt-4 text-lg text-slate-600 max-w-2xl mx-auto">
          Connected to GitHub, Supabase, Vercel, and Slack. Built in seconds.
        </p>
      </main>
    </div>
  );
}`;

  if (!isOpen) return null;

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-3 sm:p-5 bg-black/60 backdrop-blur-sm animate-in fade-in duration-200">
      <div className="relative w-full max-w-5xl h-[92vh] max-h-[820px] bg-white rounded-2xl shadow-2xl border border-[#E5E5E2] flex flex-col overflow-hidden text-left font-sans">
        {/* Top Header */}
        <div className="flex items-center justify-between px-5 py-3.5 bg-[#FBFBFA] border-b border-[#E5E5E2] shrink-0">
          <div className="flex items-center gap-3">
            <div className="w-8 h-8 rounded-xl bg-[#6D4AFF] flex items-center justify-center text-white shadow-xs">
              <Sparkles className="w-4 h-4" />
            </div>
            <div>
              <div className="flex items-center gap-2">
                <h3 className="text-sm font-bold text-[#111318]">
                  Website Builder Pipeline (4 Connected Apps Test)
                </h3>
                <span className="text-[10px] font-mono px-2 py-0.5 rounded-full bg-emerald-50 text-emerald-800 border border-emerald-200 font-bold">
                  GITHUB · VERCEL · SUPABASE · SLACK
                </span>
              </div>
              <p className="text-[11px] text-[#626873]">
                Synthesizing: <span className="font-semibold text-[#111318]">{websiteTopic}</span> (GitHub → Claude → Supabase → DeepSeek → Vercel → Slack)
              </p>
            </div>
          </div>

          <div className="flex items-center gap-2">
            <button
              onClick={handleRunPipeline}
              disabled={pipelineState === 'running'}
              className="inline-flex items-center gap-1.5 px-3 py-1.5 rounded-lg bg-white border border-[#E5E5E2] hover:border-[#D4D4CE] text-xs font-semibold text-[#111318] hover:bg-[#FAFAF8] transition-colors cursor-pointer shadow-2xs disabled:opacity-50"
            >
              <RotateCcw className="w-3.5 h-3.5 text-[#6D4AFF]" />
              <span>Re-Run Pipeline</span>
            </button>
            <button
              onClick={onClose}
              className="p-1.5 rounded-lg text-[#626873] hover:text-[#111318] hover:bg-black/[0.04] transition-colors cursor-pointer"
            >
              <X className="w-5 h-5" />
            </button>
          </div>
        </div>

        {/* 4 Connected Apps Status Strip */}
        <div className="px-5 py-2.5 bg-[#F8F9FA] border-b border-[#EFEFEA] flex items-center justify-between gap-3 overflow-x-auto text-xs shrink-0">
          <div className="flex items-center gap-4 shrink-0">
            <span className="text-[10px] font-mono uppercase font-bold text-[#8B919B]">Active Connectors:</span>
            
            <div className="flex items-center gap-1.5 bg-white border border-[#E5E5E2] px-2.5 py-1 rounded-lg shadow-2xs">
              <BrandLogo brand="github" size={13} />
              <span className="text-[11px] font-semibold text-[#111318]">GitHub</span>
              <span className="w-1.5 h-1.5 rounded-full bg-emerald-500" />
            </div>

            <div className="flex items-center gap-1.5 bg-white border border-[#E5E5E2] px-2.5 py-1 rounded-lg shadow-2xs">
              <BrandLogo brand="vercel" size={13} />
              <span className="text-[11px] font-semibold text-[#111318]">Vercel</span>
              <span className="w-1.5 h-1.5 rounded-full bg-emerald-500" />
            </div>

            <div className="flex items-center gap-1.5 bg-white border border-[#E5E5E2] px-2.5 py-1 rounded-lg shadow-2xs">
              <BrandLogo brand="supabase" size={13} />
              <span className="text-[11px] font-semibold text-[#111318]">Supabase DB</span>
              <span className="w-1.5 h-1.5 rounded-full bg-emerald-500" />
            </div>

            <div className="flex items-center gap-1.5 bg-white border border-[#E5E5E2] px-2.5 py-1 rounded-lg shadow-2xs">
              <BrandLogo brand="slack" size={13} />
              <span className="text-[11px] font-semibold text-[#111318]">Slack Alerts</span>
              <span className="w-1.5 h-1.5 rounded-full bg-emerald-500" />
            </div>
          </div>

          <div className="flex items-center gap-2 shrink-0">
            <span className="text-[11px] font-mono text-[#626873]">
              Status: {pipelineState === 'running' ? '🚀 Executing Pipeline...' : '✅ Pipeline Succeeded'}
            </span>
          </div>
        </div>

        {/* Pipeline Execution Stepper & Progress */}
        <div className="px-5 py-3 bg-[#FBFBFA] border-b border-[#E5E5E2] shrink-0">
          <div className="grid grid-cols-2 sm:grid-cols-6 gap-2">
            {steps.map((st) => (
              <div
                key={st.id}
                className={`p-2 rounded-xl border text-left transition-all ${
                  st.status === 'completed'
                    ? 'bg-white border-emerald-200 shadow-2xs'
                    : st.status === 'running'
                    ? 'bg-purple-50/50 border-[#6D4AFF] ring-2 ring-[#6D4AFF]/15 shadow-xs'
                    : 'bg-white/60 border-[#E5E5E2] opacity-60'
                }`}
              >
                <div className="flex items-center justify-between mb-1">
                  <span className="text-[9px] font-mono text-[#8B919B] font-bold">{st.step}</span>
                  {st.status === 'completed' ? (
                    <CheckCircle2 className="w-3.5 h-3.5 text-emerald-600" />
                  ) : st.status === 'running' ? (
                    <span className="w-2 h-2 rounded-full bg-[#6D4AFF] animate-ping" />
                  ) : (
                    <span className="w-2 h-2 rounded-full bg-[#D4D4CE]" />
                  )}
                </div>
                <div className="text-[11px] font-bold text-[#111318] truncate">
                  {st.connector.toUpperCase()}
                </div>
                <div className="text-[9px] text-[#626873] truncate">
                  {st.title.split(':')[1]?.trim() || st.title}
                </div>
              </div>
            ))}
          </div>
        </div>

        {/* Tab Switcher: Live Preview vs Generated Code vs Execution Trace */}
        <div className="flex items-center justify-between px-5 py-2 bg-white border-b border-[#E5E5E2] shrink-0">
          <div className="flex items-center gap-1.5">
            <button
              onClick={() => setActiveTab('preview')}
              className={`px-3 py-1.5 rounded-lg text-xs font-semibold flex items-center gap-1.5 transition-colors cursor-pointer ${
                activeTab === 'preview'
                  ? 'bg-[#6D4AFF] text-white shadow-xs'
                  : 'text-[#626873] hover:text-[#111318] hover:bg-[#F2F2EE]'
              }`}
            >
              <Globe className="w-3.5 h-3.5" />
              <span>Live Website Preview</span>
            </button>

            <button
              onClick={() => setActiveTab('code')}
              className={`px-3 py-1.5 rounded-lg text-xs font-semibold flex items-center gap-1.5 transition-colors cursor-pointer ${
                activeTab === 'code'
                  ? 'bg-[#6D4AFF] text-white shadow-xs'
                  : 'text-[#626873] hover:text-[#111318] hover:bg-[#F2F2EE]'
              }`}
            >
              <Code2 className="w-3.5 h-3.5" />
              <span>Synthesized Code (React)</span>
            </button>

            <button
              onClick={() => setActiveTab('logs')}
              className={`px-3 py-1.5 rounded-lg text-xs font-semibold flex items-center gap-1.5 transition-colors cursor-pointer ${
                activeTab === 'logs'
                  ? 'bg-[#6D4AFF] text-white shadow-xs'
                  : 'text-[#626873] hover:text-[#111318] hover:bg-[#F2F2EE]'
              }`}
            >
              <Terminal className="w-3.5 h-3.5" />
              <span>Connector Logs</span>
            </button>
          </div>

          {activeTab === 'preview' && (
            <div className="flex items-center gap-2">
              <div className="flex items-center bg-[#F0F0EC] p-0.5 rounded-lg border border-[#E5E5E2]">
                <button
                  onClick={() => setPreviewDevice('desktop')}
                  className={`p-1.5 rounded-md transition-colors cursor-pointer ${
                    previewDevice === 'desktop' ? 'bg-white text-[#111318] shadow-2xs' : 'text-[#626873]'
                  }`}
                  title="Desktop View"
                >
                  <Laptop className="w-3.5 h-3.5" />
                </button>
                <button
                  onClick={() => setPreviewDevice('mobile')}
                  className={`p-1.5 rounded-md transition-colors cursor-pointer ${
                    previewDevice === 'mobile' ? 'bg-white text-[#111318] shadow-2xs' : 'text-[#626873]'
                  }`}
                  title="Mobile View"
                >
                  <Smartphone className="w-3.5 h-3.5" />
                </button>
              </div>

              <a
                href="https://nexus-saas-website.vercel.app"
                target="_blank"
                rel="noreferrer"
                className="inline-flex items-center gap-1 text-[11px] font-bold text-[#6D4AFF] hover:underline"
              >
                <span>nexus-saas-website.vercel.app</span>
                <ExternalLink className="w-3 h-3" />
              </a>
            </div>
          )}
        </div>

        {/* Content Area */}
        <div className="flex-1 overflow-y-auto bg-[#F8F9FA] p-4 sm:p-6 flex items-center justify-center">
          {activeTab === 'preview' ? (
            /* Live Interactive Rendered Website */
            <div
              className={`w-full bg-white rounded-2xl border border-[#E5E5E2] shadow-md transition-all duration-300 flex flex-col overflow-hidden text-slate-900 ${
                previewDevice === 'mobile' ? 'max-w-sm h-[520px]' : 'max-w-4xl min-h-[460px]'
              }`}
            >
              {/* Browser Simulation Chrome Bar */}
              <div className="px-4 py-2 bg-slate-100 border-b border-slate-200 flex items-center justify-between text-xs text-slate-500 shrink-0">
                <div className="flex items-center gap-1.5">
                  <span className="w-2.5 h-2.5 rounded-full bg-rose-400" />
                  <span className="w-2.5 h-2.5 rounded-full bg-amber-400" />
                  <span className="w-2.5 h-2.5 rounded-full bg-emerald-400" />
                </div>
                <div className="px-4 py-0.5 rounded-md bg-white border border-slate-200 text-[10px] font-mono text-slate-600 truncate max-w-[280px]">
                  https://nexus-saas-website.vercel.app
                </div>
                <div className="w-6" />
              </div>

              {/* Rendered Website Body */}
              <div className="flex-1 overflow-y-auto p-6 sm:p-8 text-center bg-gradient-to-b from-white via-indigo-50/20 to-slate-50">
                {/* Website Header */}
                <div className="flex items-center justify-between pb-6 mb-8 border-b border-slate-100">
                  <div className="flex items-center gap-2">
                    <div className="w-6 h-6 rounded-lg bg-indigo-600 flex items-center justify-center text-white text-xs font-black">
                      N
                    </div>
                    <span className="font-extrabold text-sm tracking-tight text-slate-900">
                      NOVA · AI Platform
                    </span>
                  </div>
                  <div className="flex items-center gap-3 text-xs font-semibold text-slate-600">
                    <span className="hover:text-indigo-600 cursor-pointer">Platform</span>
                    <span className="hover:text-indigo-600 cursor-pointer">Security</span>
                    <span className="px-3 py-1 rounded-full bg-indigo-600 text-white cursor-pointer hover:bg-indigo-700">
                      Get Started
                    </span>
                  </div>
                </div>

                {/* Hero */}
                <div className="max-w-2xl mx-auto mb-10">
                  <span className="inline-flex items-center gap-1.5 px-3 py-1 rounded-full bg-indigo-50 border border-indigo-100 text-indigo-700 text-xs font-bold mb-4">
                    <Sparkles className="w-3.5 h-3.5 text-indigo-600" />
                    <span>BUILT AUTONOMOUSLY VIA 4 CONNECTORS</span>
                  </span>
                  <h1 className="text-3xl sm:text-4xl font-extrabold tracking-tight text-slate-950 leading-tight mb-3">
                    The Next Generation of Autonomous Agent Infrastructure
                  </h1>
                  <p className="text-sm sm:text-base text-slate-600 leading-relaxed max-w-xl mx-auto">
                    Built using GitHub (source), Claude 3.5 (code), Supabase (PostgreSQL with RLS), and deployed live to Vercel with Slack team alerts.
                  </p>
                </div>

                {/* Interactive Supabase-Connected Newsletter Form */}
                <div className="max-w-md mx-auto p-5 rounded-2xl bg-white border border-slate-200 shadow-sm mb-10 text-left">
                  <div className="flex items-center justify-between mb-2">
                    <span className="text-xs font-bold text-slate-900">Connect to Supabase DB:</span>
                    <span className="text-[10px] font-mono bg-emerald-50 text-emerald-700 px-2 py-0.5 rounded border border-emerald-200">
                      RLS ACTIVE
                    </span>
                  </div>
                  {isSubscribed ? (
                    <div className="p-3 rounded-xl bg-emerald-50 border border-emerald-200 text-emerald-800 text-xs flex items-center gap-2">
                      <CheckCircle2 className="w-4 h-4 text-emerald-600 shrink-0" />
                      <div>
                        <strong>Subscribed successfully!</strong> Record written to connected Supabase table <code>subscribers</code>.
                      </div>
                    </div>
                  ) : (
                    <form onSubmit={handleSubscribe} className="flex gap-2">
                      <input
                        type="email"
                        required
                        value={subscriberEmail}
                        onChange={(e) => setSubscriberEmail(e.target.value)}
                        placeholder="Enter email to test Supabase write..."
                        className="flex-1 px-3 py-2 text-xs rounded-xl border border-slate-200 focus:outline-none focus:border-indigo-600"
                      />
                      <button
                        type="submit"
                        className="px-4 py-2 rounded-xl bg-indigo-600 hover:bg-indigo-700 text-white text-xs font-bold transition-colors cursor-pointer"
                      >
                        Submit
                      </button>
                    </form>
                  )}
                </div>

                {/* 3 Feature Pillars */}
                <div className="grid grid-cols-1 sm:grid-cols-3 gap-4 text-left max-w-3xl mx-auto">
                  <div className="p-4 rounded-xl bg-white border border-slate-200 shadow-2xs">
                    <Database className="w-5 h-5 text-indigo-600 mb-2" />
                    <h4 className="text-xs font-bold text-slate-900 mb-1">PostgreSQL + RLS</h4>
                    <p className="text-[11px] text-slate-600">
                      Automated tenant-level isolation verified by DeepSeek-R1.
                    </p>
                  </div>
                  <div className="p-4 rounded-xl bg-white border border-slate-200 shadow-2xs">
                    <Globe className="w-5 h-5 text-blue-600 mb-2" />
                    <h4 className="text-xs font-bold text-slate-900 mb-1">Vercel Edge Network</h4>
                    <p className="text-[11px] text-slate-600">
                      Sub-20ms global edge cache with automated rollback safeguards.
                    </p>
                  </div>
                  <div className="p-4 rounded-xl bg-white border border-slate-200 shadow-2xs">
                    <MessageSquare className="w-5 h-5 text-emerald-600 mb-2" />
                    <h4 className="text-xs font-bold text-slate-900 mb-1">Slack Incident Alerts</h4>
                    <p className="text-[11px] text-slate-600">
                      Instant thread notifications for build logs and release notes.
                    </p>
                  </div>
                </div>
              </div>
            </div>
          ) : activeTab === 'code' ? (
            /* Synthesized React / Tailwind Code */
            <div className="w-full max-w-4xl bg-white rounded-2xl border border-[#E5E5E2] shadow-sm overflow-hidden flex flex-col h-[520px]">
              <div className="px-4 py-2.5 bg-[#FBFBFA] border-b border-[#E5E5E2] flex items-center justify-between text-xs">
                <span className="font-mono font-bold text-[#111318]">src/pages/GeneratedLandingPage.tsx</span>
                <button
                  onClick={() => {
                    navigator.clipboard.writeText(sampleWebsiteCode);
                    setCopiedCode(true);
                    setTimeout(() => setCopiedCode(false), 2000);
                  }}
                  className="inline-flex items-center gap-1 text-xs font-mono text-[#6D4AFF] hover:underline cursor-pointer"
                >
                  {copiedCode ? <Check className="w-3.5 h-3.5 text-emerald-600" /> : <Copy className="w-3.5 h-3.5" />}
                  <span>{copiedCode ? 'Copied' : 'Copy Code'}</span>
                </button>
              </div>
              <pre className="flex-1 p-5 overflow-y-auto font-mono text-xs leading-relaxed text-[#1F2937] bg-white text-left">
                {sampleWebsiteCode}
              </pre>
            </div>
          ) : (
            /* Connector Logs */
            <div className="w-full max-w-4xl bg-white rounded-2xl border border-[#E5E5E2] shadow-sm overflow-hidden flex flex-col h-[520px]">
              <div className="px-4 py-2.5 bg-[#FBFBFA] border-b border-[#E5E5E2] text-xs font-bold text-[#111318]">
                Real-Time Telemetry & Execution Log Stream
              </div>
              <div className="flex-1 p-4 overflow-y-auto font-mono text-xs space-y-3 bg-white text-left">
                {steps.map((st) => (
                  <div key={st.id} className="p-3 rounded-xl bg-[#F8F9FA] border border-[#EFEFEA]">
                    <div className="flex items-center justify-between mb-1">
                      <span className="font-bold text-[#111318]">{st.title}</span>
                      <span className="text-[10px] text-[#8B919B]">[{st.timestamp}]</span>
                    </div>
                    <p className="text-[11px] text-[#626873] leading-relaxed">
                      {st.detail}
                    </p>
                  </div>
                ))}
              </div>
            </div>
          )}
        </div>

        {/* Footer Actions */}
        <div className="px-6 py-3.5 bg-[#FBFBFA] border-t border-[#E5E5E2] flex flex-col sm:flex-row items-center justify-between gap-3 shrink-0 text-xs">
          <div className="flex items-center gap-2 text-[#626873]">
            <CheckCircle2 className="w-4 h-4 text-emerald-600 shrink-0" />
            <span>All 4 connected applications verified and functioning in real time.</span>
          </div>
          <div className="flex items-center gap-2">
            <Button
              size="sm"
              variant="outline"
              onClick={onClose}
              className="cursor-pointer"
            >
              Close
            </Button>
            <Button
              size="sm"
              onClick={() => {
                onClose();
                window.location.href = '/app/workflows';
              }}
              className="cursor-pointer"
            >
              <span>View in Workflows</span>
              <ArrowRight className="w-3.5 h-3.5 ml-1" />
            </Button>
          </div>
        </div>
      </div>
    </div>
  );
};
